import Header from "../components/header";
import "./globals.css";


export const metadata = {
  title: "Brewood Database",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-4 max-w-screen-xl pb-4">
          <Header/>
          {children}
        </body>
    </html>
  );
}
